# Copyright 2018 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Copyright 2020 The Province of British Columbia
#

apiVersion: template.openshift.io/v1
kind: Template
metadata:
  annotations:
    description: |
      Load generator for the Hipster Store microservice demo
      application.
  name: hipster-store-demo
objects:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: loadgenerator
    labels:
      app: hipster-store
  spec:
    selector:
      matchLabels:
        role: loadgenerator
    replicas: 1
    template:
      metadata:
        labels:
          app: hipster-store
          role: loadgenerator
        annotations:
          sidecar.istio.io/rewriteAppHTTPProbers: "true"
      spec:
        terminationGracePeriodSeconds: 5
        restartPolicy: Always
        containers:
        - name: server
          image: gcr.io/google-samples/microservices-demo/loadgenerator:v0.1.3
          env:
          - name: FRONTEND_ADDR
            value: "frontend:8080"
          - name: USERS
            value: "${USERS}"
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 300m
              memory: 512Mi
parameters:
- name: USERS
  description: |
    The number of users to simulate using the store.
  required: true
  value: "10"
